### ISSUE TITLE
Sku does not reflect barcode

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/image#2]
![image](https://user-images.githubusercontent.com/50763727/152542368-7653c22a-07de-475b-94c4-69c412f24b1f.jpeg)

![image](https://user-images.githubusercontent.com/50763727/152542385-bd64623b-1503-47f7-93fe-5b4f536b42d7.jpeg)

Change Vendor info to HOOBS Inc.

**Comment by mkellsy** [comment]
7-45114-12418-0 is an invalid UPC
The last digit should be a 3

The way UPCs work is the last digit is a check digit. 0 is an invalid check digit.
If I run the Mod 10 calculation on the first 11 digits, I come up with a 3 not a 0.
7-45114-12418-3

Who did you get these UPCs from? You may have been scammed.
