### ISSUE TITLE
add board type and ip adress to the system information

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/image#5]
![Screenshot 2022-03-02 at 11 47 24](https://user-images.githubusercontent.com/50763727/156347355-82ba0a68-de70-4be4-aff8-63799790b7f3.png)

its hard to determine which board is which. Add manufacurer and model of the board and show the ip adress here

**Comment by mkellsy** [comment]
Not easy, the board info is not part of the OS. As far as the customer is concerned, they know which board they have.

**Comment by BobbySlope** [comment]
couldnt that be hardcoded to the image?
sd card images hardcoded manufacturer and board
box hardcoded manufacturer and board
